spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/baram
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: ${PORT}
  address: localhost